#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app:
  resource: "../src/Controller/"
  type:     annotation

logout:
  path: /logout
  methods: GET

login_check:
  path: /login_check
  methods: POST


